### PR TITLE
Fix tracking header

### LINKED ISSUE #115: Tracking header does not contain proper package info
### Brief bug description

Related to #52

SDK is loading old data for the tracking header.

Value should be `jCenter;com.github.kentico:kontent-delivery;4.1.0`, or any other version in the last part.

### Repro steps

Send the request and intercept the request headers, the `X-KC-SDKID`'s value contain `localBuild;com.github.kentico:delivery;0.0.0`.

Run test `testSdkIdHeader` to easy debugging.

### Expected behavior

What the correct behavior is?

### Additional context

Proposal: 
Create a task that would create a resource file with proper values according to the https://stackoverflow.com/questions/33020069/how-to-get-version-attribute-from-a-gradle-build-to-be-included-in-runtime-swing

### PR DESCRIPTION
**Pull request by Simply007**
### Motivation

Fixes #115 

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

File: kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryClient.java [hunk 1]
```diff
@@ -53,22 +53,22 @@
...
             sdkId = String.format(
                     "%s;%s;%s",
                     repositoryHost,
                     packageId,
                     version);
             log.info("SDK ID: {}", sdkId);
         } catch (IOException e) {
-            log.info("Jar manifest read error, setting developer build SDK ID");
-            sdkId = "localBuild;kentico.kontent:delivery;0.0.0";
+            log.info("Jar manifest redeliveryad error, setting developer build SDK ID");
```
Comment (makma) [inline kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryClient.java:70]: Not sure what should be here

**Review by makma — DISMISSED** [review]

File: kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryClient.java (hunk 1 above)
Comment (Simply007) [reply kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryClient.java]: 8d1819c

**Review by makma — APPROVED** [review]

**Review by makma — DISMISSED** [review]

**Review by makma — APPROVED** [review]
